// ISO 3166-1 alpha-2 countries grouped by zone — drives the Country access picker.
export interface Country { code: string; name: string; zone: string }

export const COUNTRIES: Country[] = [
  // North America
  { code: 'US', name: 'United States', zone: 'North America' },
  { code: 'CA', name: 'Canada', zone: 'North America' },
  { code: 'MX', name: 'Mexico', zone: 'North America' },
  // Central America & Caribbean
  { code: 'GT', name: 'Guatemala', zone: 'Central America & Caribbean' },
  { code: 'BZ', name: 'Belize', zone: 'Central America & Caribbean' },
  { code: 'SV', name: 'El Salvador', zone: 'Central America & Caribbean' },
  { code: 'HN', name: 'Honduras', zone: 'Central America & Caribbean' },
  { code: 'NI', name: 'Nicaragua', zone: 'Central America & Caribbean' },
  { code: 'CR', name: 'Costa Rica', zone: 'Central America & Caribbean' },
  { code: 'PA', name: 'Panama', zone: 'Central America & Caribbean' },
  { code: 'CU', name: 'Cuba', zone: 'Central America & Caribbean' },
  { code: 'DO', name: 'Dominican Republic', zone: 'Central America & Caribbean' },
  { code: 'HT', name: 'Haiti', zone: 'Central America & Caribbean' },
  { code: 'JM', name: 'Jamaica', zone: 'Central America & Caribbean' },
  { code: 'TT', name: 'Trinidad & Tobago', zone: 'Central America & Caribbean' },
  { code: 'BS', name: 'Bahamas', zone: 'Central America & Caribbean' },
  { code: 'BB', name: 'Barbados', zone: 'Central America & Caribbean' },
  // South America
  { code: 'BR', name: 'Brazil', zone: 'South America' },
  { code: 'AR', name: 'Argentina', zone: 'South America' },
  { code: 'CL', name: 'Chile', zone: 'South America' },
  { code: 'CO', name: 'Colombia', zone: 'South America' },
  { code: 'PE', name: 'Peru', zone: 'South America' },
  { code: 'VE', name: 'Venezuela', zone: 'South America' },
  { code: 'EC', name: 'Ecuador', zone: 'South America' },
  { code: 'BO', name: 'Bolivia', zone: 'South America' },
  { code: 'PY', name: 'Paraguay', zone: 'South America' },
  { code: 'UY', name: 'Uruguay', zone: 'South America' },
  { code: 'GY', name: 'Guyana', zone: 'South America' },
  { code: 'SR', name: 'Suriname', zone: 'South America' },
  // Europe
  { code: 'GB', name: 'United Kingdom', zone: 'Europe' },
  { code: 'IE', name: 'Ireland', zone: 'Europe' },
  { code: 'FR', name: 'France', zone: 'Europe' },
  { code: 'DE', name: 'Germany', zone: 'Europe' },
  { code: 'NL', name: 'Netherlands', zone: 'Europe' },
  { code: 'BE', name: 'Belgium', zone: 'Europe' },
  { code: 'LU', name: 'Luxembourg', zone: 'Europe' },
  { code: 'CH', name: 'Switzerland', zone: 'Europe' },
  { code: 'AT', name: 'Austria', zone: 'Europe' },
  { code: 'ES', name: 'Spain', zone: 'Europe' },
  { code: 'PT', name: 'Portugal', zone: 'Europe' },
  { code: 'IT', name: 'Italy', zone: 'Europe' },
  { code: 'GR', name: 'Greece', zone: 'Europe' },
  { code: 'SE', name: 'Sweden', zone: 'Europe' },
  { code: 'NO', name: 'Norway', zone: 'Europe' },
  { code: 'DK', name: 'Denmark', zone: 'Europe' },
  { code: 'FI', name: 'Finland', zone: 'Europe' },
  { code: 'IS', name: 'Iceland', zone: 'Europe' },
  { code: 'PL', name: 'Poland', zone: 'Europe' },
  { code: 'CZ', name: 'Czechia', zone: 'Europe' },
  { code: 'SK', name: 'Slovakia', zone: 'Europe' },
  { code: 'HU', name: 'Hungary', zone: 'Europe' },
  { code: 'RO', name: 'Romania', zone: 'Europe' },
  { code: 'BG', name: 'Bulgaria', zone: 'Europe' },
  { code: 'HR', name: 'Croatia', zone: 'Europe' },
  { code: 'SI', name: 'Slovenia', zone: 'Europe' },
  { code: 'RS', name: 'Serbia', zone: 'Europe' },
  { code: 'BA', name: 'Bosnia & Herzegovina', zone: 'Europe' },
  { code: 'MK', name: 'North Macedonia', zone: 'Europe' },
  { code: 'AL', name: 'Albania', zone: 'Europe' },
  { code: 'ME', name: 'Montenegro', zone: 'Europe' },
  { code: 'EE', name: 'Estonia', zone: 'Europe' },
  { code: 'LV', name: 'Latvia', zone: 'Europe' },
  { code: 'LT', name: 'Lithuania', zone: 'Europe' },
  { code: 'UA', name: 'Ukraine', zone: 'Europe' },
  { code: 'BY', name: 'Belarus', zone: 'Europe' },
  { code: 'MD', name: 'Moldova', zone: 'Europe' },
  { code: 'RU', name: 'Russia', zone: 'Europe' },
  { code: 'MT', name: 'Malta', zone: 'Europe' },
  { code: 'CY', name: 'Cyprus', zone: 'Europe' },
  // Middle East
  { code: 'AE', name: 'United Arab Emirates', zone: 'Middle East' },
  { code: 'SA', name: 'Saudi Arabia', zone: 'Middle East' },
  { code: 'QA', name: 'Qatar', zone: 'Middle East' },
  { code: 'KW', name: 'Kuwait', zone: 'Middle East' },
  { code: 'BH', name: 'Bahrain', zone: 'Middle East' },
  { code: 'OM', name: 'Oman', zone: 'Middle East' },
  { code: 'IL', name: 'Israel', zone: 'Middle East' },
  { code: 'JO', name: 'Jordan', zone: 'Middle East' },
  { code: 'LB', name: 'Lebanon', zone: 'Middle East' },
  { code: 'TR', name: 'Turkey', zone: 'Middle East' },
  { code: 'IR', name: 'Iran', zone: 'Middle East' },
  { code: 'IQ', name: 'Iraq', zone: 'Middle East' },
  { code: 'SY', name: 'Syria', zone: 'Middle East' },
  { code: 'YE', name: 'Yemen', zone: 'Middle East' },
  // Asia
  { code: 'IN', name: 'India', zone: 'Asia' },
  { code: 'PK', name: 'Pakistan', zone: 'Asia' },
  { code: 'BD', name: 'Bangladesh', zone: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', zone: 'Asia' },
  { code: 'NP', name: 'Nepal', zone: 'Asia' },
  { code: 'BT', name: 'Bhutan', zone: 'Asia' },
  { code: 'MV', name: 'Maldives', zone: 'Asia' },
  { code: 'CN', name: 'China', zone: 'Asia' },
  { code: 'HK', name: 'Hong Kong', zone: 'Asia' },
  { code: 'TW', name: 'Taiwan', zone: 'Asia' },
  { code: 'JP', name: 'Japan', zone: 'Asia' },
  { code: 'KR', name: 'South Korea', zone: 'Asia' },
  { code: 'KP', name: 'North Korea', zone: 'Asia' },
  { code: 'MN', name: 'Mongolia', zone: 'Asia' },
  { code: 'SG', name: 'Singapore', zone: 'Asia' },
  { code: 'MY', name: 'Malaysia', zone: 'Asia' },
  { code: 'ID', name: 'Indonesia', zone: 'Asia' },
  { code: 'TH', name: 'Thailand', zone: 'Asia' },
  { code: 'VN', name: 'Vietnam', zone: 'Asia' },
  { code: 'PH', name: 'Philippines', zone: 'Asia' },
  { code: 'MM', name: 'Myanmar', zone: 'Asia' },
  { code: 'KH', name: 'Cambodia', zone: 'Asia' },
  { code: 'LA', name: 'Laos', zone: 'Asia' },
  { code: 'BN', name: 'Brunei', zone: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan', zone: 'Asia' },
  { code: 'UZ', name: 'Uzbekistan', zone: 'Asia' },
  { code: 'TM', name: 'Turkmenistan', zone: 'Asia' },
  { code: 'KG', name: 'Kyrgyzstan', zone: 'Asia' },
  { code: 'TJ', name: 'Tajikistan', zone: 'Asia' },
  { code: 'AF', name: 'Afghanistan', zone: 'Asia' },
  { code: 'GE', name: 'Georgia', zone: 'Asia' },
  { code: 'AM', name: 'Armenia', zone: 'Asia' },
  { code: 'AZ', name: 'Azerbaijan', zone: 'Asia' },
  // Africa
  { code: 'ZA', name: 'South Africa', zone: 'Africa' },
  { code: 'EG', name: 'Egypt', zone: 'Africa' },
  { code: 'NG', name: 'Nigeria', zone: 'Africa' },
  { code: 'KE', name: 'Kenya', zone: 'Africa' },
  { code: 'GH', name: 'Ghana', zone: 'Africa' },
  { code: 'ET', name: 'Ethiopia', zone: 'Africa' },
  { code: 'TZ', name: 'Tanzania', zone: 'Africa' },
  { code: 'UG', name: 'Uganda', zone: 'Africa' },
  { code: 'DZ', name: 'Algeria', zone: 'Africa' },
  { code: 'MA', name: 'Morocco', zone: 'Africa' },
  { code: 'TN', name: 'Tunisia', zone: 'Africa' },
  { code: 'LY', name: 'Libya', zone: 'Africa' },
  { code: 'SD', name: 'Sudan', zone: 'Africa' },
  { code: 'AO', name: 'Angola', zone: 'Africa' },
  { code: 'MZ', name: 'Mozambique', zone: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', zone: 'Africa' },
  { code: 'ZM', name: 'Zambia', zone: 'Africa' },
  { code: 'BW', name: 'Botswana', zone: 'Africa' },
  { code: 'NA', name: 'Namibia', zone: 'Africa' },
  { code: 'RW', name: 'Rwanda', zone: 'Africa' },
  { code: 'SN', name: 'Senegal', zone: 'Africa' },
  { code: 'CI', name: "Côte d'Ivoire", zone: 'Africa' },
  { code: 'CM', name: 'Cameroon', zone: 'Africa' },
  { code: 'CD', name: 'DR Congo', zone: 'Africa' },
  { code: 'MU', name: 'Mauritius', zone: 'Africa' },
  // Oceania
  { code: 'AU', name: 'Australia', zone: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', zone: 'Oceania' },
  { code: 'FJ', name: 'Fiji', zone: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', zone: 'Oceania' },
];

export const ZONES: string[] = [
  'North America',
  'Central America & Caribbean',
  'South America',
  'Europe',
  'Middle East',
  'Asia',
  'Africa',
  'Oceania',
];

export const COUNTRY_NAME: Record<string, string> = Object.fromEntries(COUNTRIES.map((c) => [c.code, c.name]));
